import type { Metadata } from "next";
import "./globals.css";
import AuthState from "@/context/Auth/AuthState";
import Navbar from "@/components/Navbar";
import SocketState from "@/context/Socket/SocketState";
import GameState from "@/context/Game/GameState";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthState>
          <SocketState>
            <Navbar />
            <GameState>
              {children}
            </GameState>
          </SocketState>
        </AuthState>
      </body>
    </html >
  );
}
