import type { Metadata } from "next";
import "./globals.css";
import AuthState from "@/context/Auth/AuthState";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <AuthState>
          {/* <Navbar /> */}
          {children}
        </AuthState>
      </body>
    </html>
  );
}
